apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: salinesel-in
  replicas: 2
  template:
    metadata:
      labels:
        app: salinesel-in
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccount: salinesel-in
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.101.0-ext-alpine
          workingDir: /salinesel.in
          # command:
          #   - hugo server -p 8080
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /salinesel.in
              name: gce-disk
      volumes:
        - name: gce-disk
          persistentVolumeClaim:
            claimName: nfs
