apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      labels:
        app: salinesel-in
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccount: salinesel-in
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.101.0-alpine
          workingDir: /src
          command:
            - hugo server -D
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /src
              name: gce-disk
      volumes:
        - name: gce-disk
          gcePersistentDisk:
            pdName: salinesel-in-nfs-disk
            fsType: ext4
