apiVersion: v1
kind: Pod
metadata:
  name: seed-nfs
  namespace: salinesel-in
  labels:
    name: seed-nfs
spec:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  serviceAccount: salinesel-in
  containers:
    - name: seed-nfs
      image: alpine:latest
      workingDir: /salinesel.in
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /salinesel.in
          name: gce-disk
  volumes:
    - name: gce-disk
      persistentVolumeClaim:
        claimName: nfs
