apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      labels:
        app: salinesel-in
    spec:
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.93.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /src
              name: salinesel-in
      volumes:
        - name: salinesel-in
          persistentVolumeClaim:
            claimName: salinesel-in
