apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/gcsfuse: localhost/fuse
      labels:
        app: salinesel-in
    spec:
      volumes:
        - name: creds
          secret:
            secretName: salinesel-in
      initContainers:
        - name: gcsfuse
          image: levkuznetsov/gcsfuse-docker:latest
          command:
            - gcsfuse
          args:
            - salinesel-in-30df37b
            - /mnt
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              smarter-devices/fuse: 1
              memory: 512Mi
            requests:
              smarter-devices/fuse: 1
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/creds
              name: creds
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/creds/credentials.json
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.93.2
          workingDir: /mnt
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
