apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      labels:
        app: salinesel-in
    spec:
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.93.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      initContainers:
        - name: gcsfuse-mounter
          image: levkuznetsov/gcsfuse-docker:latest
          command: ["gcsfuse", "--foreground", "bucket-name", "/src"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          envFrom:
            - secretRef:
                name: salinesel-in
