apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/gcsfuse: localhost/fuse
      labels:
        app: salinesel-in
    spec:
      volumes:
        - name: web-bucket
          emptyDir: {}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccount: salinesel-in
      initContainers:
        - name: gcsfuse
          image: us-west3-docker.pkg.dev/elite-protocol-319303/salinesel-in/gcsfuse:0.41.2
          command:
            - gcsfuse
          args:
            - --implicit-dirs
            - salinesel-in-30df37b
            - /src
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              smarter-devices/fuse: "1"
              memory: 512Mi
            requests:
              smarter-devices/fuse: "1"
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: web-bucket
              mountPath: /src
      containers:
        - name: salinesel-in
          image: klakegg/hugo:0.93.2
          workingDir: /mnt
          command:
            - sleep
          args:
            - infinity
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
              smarter-devices/fuse: "1"
            requests:
              memory: "128Mi"
              cpu: "500m"
              smarter-devices/fuse: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: web-bucket
              mountPath: /src
