apiVersion: apps/v1
kind: Deployment
metadata:
  name: salinesel-in
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: salinesel-in
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/salinesel-in: localhost/fuse
      labels:
        app: salinesel-in
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccount: salinesel-in
      containers:
        - name: salinesel-in
          image: us-west3-docker.pkg.dev/elite-protocol-319303/salinesel-in/gcsfuse-hugo:0.41.2
          workingDir: /src
          command:
            - gcsfuse --implicit-dirs salinesel-in-30df37b /src
            - hugo server -D
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
              smarter-devices/fuse: "1"
            requests:
              memory: "128Mi"
              cpu: "500m"
              smarter-devices/fuse: "1"
          ports:
            - containerPort: 8080
