apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salinesel-in
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: salinesel-in
  resources:
    requests:
      storage: 1Gi
