apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salinesel.in
  namespace: salinesel.in
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
