apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName: "regionalpd-storageclass"
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: salinesel.in
    name: salinesel.in
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/elite-protocol-319303/zones/us-west3-c/disks/salineselin-a263a68
