name: push-registry
on:
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: login to artifact registry
        uses: docker/login-action@v2
        with:
          registry: us-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: us-west3-docker.pkg.dev/elite-protocol-319303/salinesel-in/gcsfuse-hugo:0.41.2
          context: .
