name: seed-nfs
on:
  - workflow_dispatch

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: setup hugo
        run: sudo apt-get install hugo

      - name: download modules
        run: go mod download

      - name: login to gcp
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: build hugo
        run: hugo
        working-directory: salinesel.in

      - name: seed nfs
        run: |
          NAMESPACE=salinesel-in
          POD=seed-nfs
          kubectl apply -f ./k8s/tools/seed.yml -n ${NAMESPACE}
          kubectl cp ./salinesel.in ${NAMESPACE}/${POD}:/salinesel.in
          kubectl delete pod ${POD} -n {$NAMESPACE}
